module.exports={
	namiarusurfstudio:{
		name:"namiarusurfstudio",
		imageUrl:"https://namiaru.yibnb.com/images/bg.jpg",
		url:"https://namiaru.yibnb.com",
		address:"宜蘭縣頭城鎮環鎮東路二段668巷8號",
		contact:"0968-369853",
		email:"namiarusurfstudio@gmail.com",
		lineId:"@420msvqa",
		instagramUrl:"https://www.instagram.com/namiarusurfstudio",
		facebookUrl:"https://www.facebook.com/808387692583232"
	},
	一間衝浪店:{
		name:"一間衝浪店",
		imageUrl:"https://i.imgur.com/bHMjsw1.jpg",
		url:"https://www.facebook.com/aloha.hisurf",
		address:"宜蘭縣頭城鎮濱海路二段332巷29-1號",
		contact:"03 977 7517",
		email:"namiarusurfstudio@gmail.com",
		lineId:"@420msvqa",
		instagramUrl:"https://www.instagram.com/namiarusurfstudio",
		facebookUrl:"https://www.facebook.com/aloha.hisurf"
	},
	浪花舞:{
		name:"浪花舞",
		imageUrl:"https://www.wavedancelife.com/wp-content/uploads/2020/03/%E6%B5%AA%E8%8A%B1%E8%88%9E-BlackLogo.png",
		url:"https://www.wavedancelife.com/",
		address:"宜蘭縣頭城鎮濱海路二段405號",
		contact:"03 977 7671",
		email:null,
		lineId:null,
		instagramUrl:"https://www.instagram.com/wavedancesurflife",
		facebookUrl:"https://www.facebook.com/wavedancesurflife"
	},
	吉鵝:{
		name:"吉鵝",
		imageUrl:"https://i3.wp.com/asif-fashion.com/wp-content/uploads/2018/11/Jill3.jpg",
		url:"https://www.instagram.com/jill_loves_yoga_surf/",
		address:null,
		contact:"https://www.instagram.com/jill_loves_yoga_surf/",
		email:null,
		lineId:null,
		instagramUrl:"https://www.instagram.com/jill_loves_yoga_surf/",
		facebookUrl:null
	},
	外澳飯:{
		name:"外澳飯",
		imageUrl:"https://pic.pimg.tw/fennyfenny/1597060275-3231545206-g_n.jpg",
		url:"https://www.instagram.com/waiao_bon_appetit/",
		address:null,
		contact:"https://www.instagram.com/waiao_bon_appetit/",
		email:null,
		lineId:null,
		instagramUrl:"https://www.instagram.com/waiao_bon_appetit/",
		facebookUrl:"https://www.facebook.com/Waiao.bonappetit"
	}/*,
	豆你丸:{
		name:"豆你丸",
		imageUrl:"https://i.imgur.com/YVrPbWm.jpg",
		url:"https://www.facebook.com/DouNiWanZi",
		address:"桃園市大溪區和平路3號",
		contact:"03 387 8100",
		email:null,
		lineId:null,
		instagramUrl:null,
		facebookUrl:"https://www.facebook.com/DouNiWanZi"
	}*/
};
