module.exports={
	namiarusurfstudio:{
		name:"namiarusurfstudio",
		imageUrl:"https://namiaru.yibnb.com/images/bg.jpg",
		url:"https://namiaru.yibnb.com",
		address:"宜蘭縣頭城鎮環鎮東路二段668巷8號",
		phone:"0968-369853",
		email:"namiarusurfstudio@gmail.com",
		lineId:"@420msvqa",
		instagramUrl:"https://www.instagram.com/namiarusurfstudio",
		facebookUrl:"https://www.facebook.com/808387692583232"
	},
	一間衝浪店:{
		name:"一間衝浪店",
		imageUrl:"https://i.imgur.com/bHMjsw1.jpg",
		url:"https://www.facebook.com/aloha.hisurf",
		address:"宜蘭縣頭城鎮濱海路二段332巷29-1號",
		phone:"03-9777517",
		email:"namiarusurfstudio@gmail.com",
		lineId:"@420msvqa",
		instagramUrl:"https://www.instagram.com/namiarusurfstudio",
		facebookUrl:"https://www.facebook.com/aloha.hisurf"
	},
	//要測試沒imageUrl=>沒hero、沒email、沒下面1/3或2/3、（下面三個都沒=>沒footer）
	test:{
		name:"test",
		imageUrl:"https://i.imgur.com/bHMjsw1.jpg",
		url:"https://www.facebook.com/aloha.hisurf",
		address:"宜蘭縣頭城鎮濱海路二段332巷29-1號",
		phone:"03-9777517",
		email:null,
		lineId:"@420msvqa",
		instagramUrl:null,
		facebookUrl:null
	}
};
